name: Simplified Update Package

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run update package script
      run: ./update-package.ps1
      working-directory: .github\workflows

    - name: Run validation checks
      run: ./run-validation-checks.ps1
      working-directory: .github\workflows

    # Create Pull Request
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Update Package"
        body: "This is an automated pull request to update the package."
        branch: "feature/update-package-${{ github.run_number }}"