name: Scheduled Package Maintenance

on:
  schedule:
    - cron: '0 0 15 * *' # Every 15th day
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened # pull request

jobs:
  update:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run update package script
      run: ./update-package.ps1
      working-directory: .github\workflows

    # Create Pull Request
    - name: Create Pull Request
      if: env.updated == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Update Package"
        body: "This is an automated pull request to update the package."
        branch: "feature/update-package-${{ github.run_number }}"

    # Install Chocolatey
    - name: Install Chocolatey
      if: env.updated == 'true'
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    # Add API Key for Chocolatey
    - name: Add API Key
      if: env.updated == 'true'
      run: choco apikey add --source "https://push.chocolatey.org/" --key "${{ secrets.CHOCO_API_KEY }}"

    # Push Chocolatey Package
    - name: Push Package
      if: env.updated == 'true'
      run: choco push iis-compression.nupkg --source "https://push.chocolatey.org/"