name: Simplified Update Package

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # run update-package.ps1
    - name: Run update package script
      run: ./update-package.ps1